### DISCUSSION TITLE
generator sanitizing/renaming variables with special characters

### DISCUSSION THREAD

**Discussion by bolanosdev** [acacode/swagger-typescript-api#869] [General]
hi.

i have an openapi spec where we have query variables with special characters
example :
```
...
parameters:
 - name: foo_bar.baz
          in: query
          description: lorem ipsum
          schema: { type: string }
          
...
```

and when i run the generator the query params sanitized removing special characters and are renamed to fooBarBaz

is there a configuration option so the generator will allow me to return the query params as strings?
actual: 

```
  apiOperation: (
    tag: string,
    query: {
      ...
      foBarBaz?: string;
      /** Filter returned accounts by account status */

    },
    params: RequestParams = {}
  ) => ....;
    
```

expected:

```
  apiOperation: (
    tag: string,
    query: {
      ...
      'foo_bar.baz'?: string;
    },
    params: RequestParams = {}
  ) => ....;
    
```
