### ISSUE TITLE
Path parameter interpreted as template literal when 

### ISSUE THREAD

**Issue by thuoe** [acacode/swagger-typescript-api#143]
I have a query parameter defined called "riskGroup" in my swagger yml like so: 

```
/efficientPortfolio/getPortfolios/{riskGroup}:
      get:
        summary: Efficient Portfolio Parameters
        description: ''
        operationId: getEfficientPortfolios
        produces:
          - application/json
        parameters:
          - name: riskGroup
            in: path
            description: User's risk benchmark to which their request can be evaluated.
           ....
     x-swagger-router-controller: "getEfficientPortfolios"
```

However, once generated the controller in typescript interprets the path parameter as a template literal like so: 

![image](https://user-images.githubusercontent.com/15982721/106165469-0eb0a600-6183-11eb-9f6e-58e09cacf173.png)

Any ideas on what I am doing incorrectly?
