### ISSUE TITLE
Handling required + readonly fields on creation

### ISSUE THREAD

**Issue by jeking3** [acacode/swagger-typescript-api#273]
I am using django + drf + drf_spectacular.  On one API the resulting post schema looks like this:

```
    post:
      operationId: projects_create
      description: ''
      tags:
      - projects
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Project'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Project'
        required: true
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
          description: ''
```

The definition of Project is:

```
    Project:
      type: object
      properties:
        url:
          type: string
          format: uri
          readOnly: true
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
          maxLength: 256
        description:
          type: string
      required:
      - id
      - name
      - url
```

When I view this in Swagger UI, the POST here correctly shows the schema for the post needs "name" and "description", and the result gets all four fields:

![image](https://user-images.githubusercontent.com/11771245/122835310-1dc4fb80-d2be-11eb-824c-0f8807e3e04e.png)

The code generation in this project makes a single Project interface which requires "url" and "id", but it seems the official swagger interpretation of required fields that are readonly are not included on a POST.  Here's what this project creates:

```
export interface Project {
  /** @format uri */
  url: string;
  /** @format uuid */
  id: string;
  name: string;
  description?: string;
}
```

It then applies this Project to the create call:

```
  /**
   * No description
   * @tags projects
   * @name ProjectsCreate
   * @request POST:/api/v1/projects/
   * @secure
   * @response `201` `Project`
   */
  export namespace ProjectsCreate {
    export type RequestParams = {};
    export type RequestQuery = {};
    export type RequestBody = Project;
    export type RequestHeaders = {};
    export type ResponseBody = Project;
  }
```

This means that in order to create the project, one must provide the identity of the object that will be created, but it is readonly.  It would seem to me that if a field is required but readonly, on a command like POST where the id is not part of the path, the required+readonly fields should be dropped from the structure; in this case the code generator should make a ProjectCreate interface that takes only "name" and "description" for the POST command?  This is not happening, so the client is not usable.  Give the Swagger UI looks correct, perhaps the interpretation of the swagger is incorrect in this project?

To solve this, if something is being created I would think any readonly field from the interface would need to be dropped, and a "create" variable of that interface would need to be emitted and used in the RequestBody for a Create?
