### ISSUE TITLE
prefixItems with the same minItems and maxItems value should generate tuples

### ISSUE THREAD

**Issue by brookjordan** [acacode/swagger-typescript-api#285]
For example, if we want a list of lat, lon coordinates, this:
```yaml
type: array
items:
  type: array
  minItems: 2
  maxItems: 2
  prefixItems:
    - number
    - number
```
should generate:
```
[number, number][];
```
rather than the current:
```
any[][]
```

----

For now the closest we seem to be able to get is:
```yaml
type: array
items:
  type: array
  items:
    type: number
```
generating:
```
number[][]
```
