### ISSUE TITLE
additionalProperties management problem in Swagger 2

### ISSUE THREAD

**Issue by paztis** [acacode/swagger-typescript-api#343]
In swagger 2, additionalProperties are very limited. They didn't support the true and {} values.
To replace this they define it like this

```
  MyObject:
    type: object
    properties:
      id:
        type: string
      additionalProperties:
        type: object
```

It works only because in java like words String, Boolean and Numbers are Objects

in swagger 2, it must be transpiled in 

```
export interface MyObject {
    id?: string;
    [key: string]: {}; // or [key: string]: any
} 
```

but for now it is transpiled in 
```
export interface MyObject {
    id?: string;
}
```

result is the same If I try  to transpile below code 
```
  MyObject:
    type: object
    properties:
      id:
        type: string
    additionalProperties: {}
```

The only case the correctly works is
```
  MyObject:
    type: object
    properties:
      id:
        type: string
    additionalProperties: true
```

Swagger file is correctly converted with Swager.io typescript generators

Is it possible to fix it ?

**Comment by paztis** [comment]
Problem came from schema.js file
```

  if (additionalProperties === true) {
    propertiesContent.push({
      $$raw: { additionalProperties },
      description: "",
      isRequired: false,
      field: `[key: ${TS_KEYWORDS.STRING}]: ${TS_KEYWORDS.ANY}`,
    });
  }

  return propertiesContent;
```

It seams you only support the additionalProperties: true case, not the others

**Comment by paztis** [comment]
There's another more problematic case

```
  MyObject:
    type: object
    additionalProperties:
        type: object
```

Means in openApi 3 ```Record<string, object>```
While in Swagger 2.0 it means ```Record<string, any>```


Because of this problem, server code generated by swagger.io is not compatible with client code generated with your library.
