### ISSUE TITLE
Nullable not included in type definition

### ISSUE THREAD

**Issue by bluenote10** [acacode/swagger-typescript-api#36]
According to [this information](https://stackoverflow.com/a/48114322/1804173) it should be possible to define a nullable type in OpenAPI 3.0.x like this:

```yaml
schemas:
  StringNullable:
    type: string
    nullable: true
```

However this generates the following TypeScript:

```ts
export type StringNullable = string;
```

I was hoping it would create:

```ts
export type StringNullable = string | null;
```
