### ISSUE TITLE
maxItems \ minItems support?

### ISSUE THREAD

**Issue by inomn** [acacode/swagger-typescript-api#489]
Hi! Any chance to generate more strict types when max\min items are defined?

**Example input scheme:**
```
        point:
          title: Point
          maxItems: 2
          minItems: 2
          type: array
          items:
            type: number
```

*Current output:*
```
point: number[];
```

Expected:
```
point: [number, number];
```
