### ISSUE TITLE
[BUG] nullable enum with integer values

### ISSUE THREAD

**Issue by h3llomoto** [acacode/swagger-typescript-api#543]
Hello, there is a problem while generating nullable enum with int values
```
prop:
  type: integer
  x-nullable: true
  enum:
    [ 0, 1, 2, 3, 4, 5 ]
```
generates to
```
prop?: "0" | "1" | "2" | "3" | "4" | "5" | null;
```
but without `x-nullable: true` generates to
```
prop?: 0 | 1 | 2 | 3 | 4 | 5;
```
