### ISSUE TITLE
Add an option to disable converting path params into camelCase

### ISSUE THREAD

**Issue by Quatters** [acacode/swagger-typescript-api#592]
If I have a snake_case path param in original schema like

```yaml
/some/{path_param}/:
    ...
    parameters:
    - name: path_param
      in: path
      required: true
      type: string
```

then it'll be converted into camelCase in generated route (using `generateRouteTypes: true`):

```ts
'/some/{path_param}/': {
    get: {
      params: {
        pathParam: number;
      };
      ...
    };
  }
```

I guess I found this place and I see that this behavior is hard-coded: 
https://github.com/acacode/swagger-typescript-api/blob/2b6db2346028fe6fb1f311bf5b1221a89837032e/src/schema-routes/schema-routes.js#L252

The problem is that in our project we don't want path params to be converted into camelCase. We expecting that they are stay as given by schema. 

Would be nice to have an option for `generateApi` for disabling this converting. Something like

```ts
return generateApi({
  generateRouteTypes: true,
  pathParamsInCamelCase: false, // true by default for example
});
```
