### ISSUE TITLE
BigInt type for format: int64 types in swagger

### ISSUE THREAD

**Issue by mr-tron** [acacode/swagger-typescript-api#687]
Can I make (maybe using --custom or --templates)  with this generator types BigInt  for and only for
```
type: integer
format: int64
```
?
For example i have structure
```
pet:
  type: object
  properties:
    age:
      type: integer
    unique_big_id:
      type: integer
      format: int64
```
Can i get generated type 
```
export interface Pet {
  age: number;
  unique_big_id: BigInt;
}
```
and marshal response from response from server `{ "unique_big_id" : 9223372036854775807, "age": 123 }` to Pet without losing precision to 9223372036854775000?
