### ISSUE TITLE
Bug: discriminator example isn’t outputting Mapping as a generic

### ISSUE THREAD

**Issue by brookjordan** [acacode/swagger-typescript-api#688]
Package version: `13.0.3`

Compiling the example discriminator Pet types example fails because it isn’t outputting the `Mapping` type as a generic.

This yaml:
```yml
components:
  schemas:
    Pet:
      type: object
      required:
        - pet_type
      properties:
        pet_type:
          type: string
      discriminator:
        propertyName: pet_type
        mapping:
          cachorro: '#/components/schemas/Dog'
          cat: '#/components/schemas/Cat'
    Cat:
      allOf:
        - '$ref': '#/components/schemas/Pet'
        - type: object
          properties:
            name:
              type: string
    Dog:
      allOf:
        - '$ref': '#/components/schemas/Pet'
        - type: object
          properties:
            bark:
              type: string
```

Is giving this invalid typescript:

```ts
export type Pet = BasePet & (BasePetPetTypeMapping<'cachorro', Dog> | BasePetPetTypeMapping<'cat', Cat>);

export type Cat = BasePet & {
  name?: string;
};

export type Dog = BasePet & {
  bark?: string;
};

export interface BasePet {
  pet_type: string;
}

export type BasePetPetTypeMapping = {
  pet_type: Key;
} & Type;
```

`BasePetPetTypeMapping` should be generic:

```ts
export type BasePetPetTypeMapping<Key, Type> = {
  pet_type: Key;
} & Type;
```
